BUILD_VERSION := $(shell grep 'version:' pubspec.yaml | awk '{print $$2}')

name: Build and deploy flutter web app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'main'
      - run: flutter pub get
      - run: flutter config --enable-web
      - run: flutter build web --base-href '/'
      
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - run: git --work-tree build/web add --all
      - run: git commit -m "Deploy Version $(BUILD_VERSION)"
      - run: git push origin HEAD:gh_pages --force