// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdihSC4tMVGOLtcEw7WiXKJr7QStZ5LRU',
    appId: '1:575133874268:web:1b31ea3e61d4524e460e99',
    messagingSenderId: '575133874268',
    projectId: 'motd-light-cc',
    authDomain: 'motd-light-cc.firebaseapp.com',
    storageBucket: 'motd-light-cc.appspot.com',
    measurementId: 'G-W081MJMLWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0Y-0wbaK3rQyDPhleacSBtwU_CcLi2F0',
    appId: '1:575133874268:android:88b0ae4ddec3d9eb460e99',
    messagingSenderId: '575133874268',
    projectId: 'motd-light-cc',
    storageBucket: 'motd-light-cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJUnt2PWNrNsZ-J-znz0eEHa4N72gLnyA',
    appId: '1:575133874268:ios:29715bc79e7bef2f460e99',
    messagingSenderId: '575133874268',
    projectId: 'motd-light-cc',
    storageBucket: 'motd-light-cc.appspot.com',
    iosBundleId: 'com.example.motd',
  );
}
